### ISSUE TITLE
Password inside public config =)

### ISSUE THREAD

**Issue by fagci** [M7SPI/Quasheng-UV-K5-UK-North-West-Channel-Settings-File#1]
https://github.com/M7SPI/Quasheng-UV-K5-UK-North-West-Channel-Settings-File/blob/f966e208debb159b7def9033aa09134f4a9ca505/M7SPIPublic_revision4.cxf#L34

Also, trere is VOX level. I think, this need to be default values.

**Comment by M7SPI** [comment]
Bit of a a couple of strange ones them has firstly the is no password set on the radio itself so presume the  <AccessPwd>/DGzTcf8uU4=</AccessPwd> defaults to no password within the radio firmware.
Secondly on the radio itself VOX level is set to "off" but there is only options for vox Level 1-10 through the cps software and no off option.
